pipeline:
  please:
    image: nexus.admin.sharecare.com/drone-nexus-docker:4.4.1
    environment:
      PLUGIN_DAEMON_OFF: true
    version: jq -r .version package.json

  npmrc:
    image: mhart/alpine-node
    privileged: true
    commands:
      - ifconfig
      - apk add --no-cache --update mtu
      - npm i -ddd debug
      - npm i -ddd @sharecare/maestro-dsl
