pipeline:
  something:
    image: busybox
    commands:
      - sleep 10
      - ls -al
      
  docker:
    image: docker
    env:
      - DOCKER_API_VERSION: 1.23
    commands:
      - docker images
      - docker build -t buts .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

#  slack:
#    image: themaz/drone-slack
#    webhook: https://hooks.slack.com/services/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
#    channel: drone_builds
#    username: incoming-webhook
#    debug: true
#    template: Build number {{ build.number }} has completed (via {{ uppercase build.event }})

  teams:
    image: cloudsc/drone-teams-notification
    webhook: "https://outlook.office.com/webhook/87b7de90-c5c8-4dc9-9235-c1fe3bd41350@4791286b-0707-4782-8dae-89fe4a320b09/IncomingWebhook/8bfd7b92b7c243b5be907232502cd5f5/73208d33-54b5-4aa8-af10-139d155a7ef2"

+branches:
  - develop
  - master
