pipeline:  
      
  docker:
    image: nexus.admin.sharecare.com/drone-nexus-docker:4.4.1
    environment:
      PLUGIN_BUILD_ARGS: --network=host
    version: jq -r .version package.json
    commands: 
      - set
      - ls -al /secrets
      - /bin/drone-nexus-docker

  npmrc:
    image: mhart/alpine-node:10
    environment:
      - NPM_CONFIG_USERCONFIG=/secrets/.npmrc
    commands:
      - npm i -ddd @sharecare/custom-error
