pipeline:  
  something:
    image: mhart/alpine-node:8
    commands: 
      - cp /secrets/.npmrc $HOME/.npmrc
      - npm i @sharecare/maestro-dsl
    volumes:
      - /secrets:/secrets

  docker:
    image: cloudsc/drone-nexus-docker
    repo: delete-me
    debug: true
    secrets: [ docker_username, docker_password ]
