pipeline:  
      
  docker:
    image: nexus.admin.sharecare.com/drone-nexus-docker
    environment:
      DOCKER_OPTS: --network=host
      PLUGIN_DEBUG: true
      PLUGIN_LAUNCH_DEBUG: true
    version: jq -r .version package.json
    commands: 
      - set | grep PLUGIN
      - /bin/drone-nexus-docker

  npmrc:
    image: mhart/alpine-node:10
    environment:
      - NPM_CONFIG_USERCONFIG=/secrets/.npmrc
    commands:
      - npm i -ddd @sharecare/custom-error
      - ls -al
