pipeline:  
  something:
    image: busybox
    commands: 
      - ls -al

  docker:
    image: plugins/docker
    repo: cloudsc/delete-me
    debug: true
    secrets: [ docker_username, docker_password ]
