pipeline:
  assemble:
    image: gempesaw/docker-sbt:0.13.11
    commands:
      - mkdir -p $HOME/.sbt/0.13/plugins/
      - cp /secrets/.credentials $HOME/.ivy2/
      - cp /secrets/credentials.sbt $HOME/.sbt/0.13/plugins/plugins.sbt
      - sbt run
