pipeline:
  first:
    image: cloudsc/drone-teams-notification:manual
    webhook: https://outlook.office.com/webhook/87b7de90-c5c8-4dc9-9235-c1fe3bd41350@4791286b-0707-4782-8dae-89fe4a320b09/IncomingWebhook/8bfd7b92b7c243b5be907232502cd5f5/73208d33-54b5-4aa8-af10-139d155a7ef2
    why: not
      
  something:
    image: busybox
    commands:
      - ls -al
