pipeline:
  please:
    image: nexus.admin.sharecare.com/drone-nexus-docker:4.4.1
    environment:
      PLUGIN_DAEMON_OFF: true
    pull: true
    version: jq -r .version package.json
    
  npmrc:
    image: mhart/alpine-node
    environment:
      - NPM_CONFIG_USERCONFIG=/secrets/.npmrc
    commands:
      - nslookup nexus.admin.sharecare.com
      - apk add --no-cache --update mtu
      - npm i -ddd debug
      - ls -al /secrets
      - cat /secrets/.npmrc | grep registry
      - mtu -d nexus.admin.sharecare.com
      - npm i -ddd @sharecare/maestro-dsl
    
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1460
