pipeline:  
  something:
    image: busybox
    commands: 
      - ls -al

  docker:
    image: plugins/docker
    repo: cloudsc/delete-me
    debug: true
    custom_dns: 8.8.8.8
    dns: 8.8.8.8
    secrets: [ docker_username, docker_password ]

docker host? 
