pipeline:  
  npmrc:
    image: mhart/alpine-node:10
    environment:
      - NPM_CONFIG_USERCONFIG=/secrets/.npmrc
    commands:
      - npm i @sharecare/authorization 
      - ls -al
      
  lololool:
    image: mongo
    commands: 
      - mongo mongodb://mongo:27017
      
  whee:
    image: nexus.admin.sharecare.com/drone-nexus-docker
    version: jq -r .version package.json
    commands:
    - set
    - env
    - cat /etc/resolv.conf

services:
  mongo:
    image: mongo
