pipeline:
  please:
    image: nexus.admin.sharecare.com/drone-nexus-docker
    version: jq -r .version package.json
    privileged: true
    commands:
      - set | grep PLUGIN
      - cat /etc/resolv.conf
      - apk add --no-cache --update curl
      - cat /etc/resolv.conf
      - /bin/drone-nexus-docker
