pipeline:  
  something:
    image: busybox
    commands: 
      - ls -al
      - echo 'yup'

  docker:
    image: plugins/docker
    repo: cloudsc/delete-me
    dns: 8.8.8.8
    secrets: [ docker_username, docker_password ]
