pipeline:  
  lololool:
    image: mongo
    commands: 
      - mongo mongodb://mongo:27017    
      
  npmrc:
    image: mhart/alpine-node:8
    environment:
      - NPM_CONFIG_USERCONFIG=/secrets/.npmrc
    commands:
    - npm i @sharecare/authorization 
      - ls -al
    volumes:
      - /secrets:/secrets


services:
  mongo:
    image: mongo
