pipeline:
  please:
    image: nexus.admin.sharecare.com/drone-nexus-docker:4.4.1
    version: jq -r .version package.json

  npmrc:
    image: mhart/alpine-node
    environment:
      - NPM_CONFIG_USERCONFIG=/secrets/.npmrc
    commands:
      - ifconfig
      - cat /etc/resolv.conf
      - cat /etc/hosts
      - cat /secrets/.npmrc | grep -v Token | grep -v token
      - apk add --no-cache --update curl
      - curl nexus.admin.sharecare.com
      - npm i debug
      - npm i @sharecare/maestro-dsl
      - echo 'sixty 5 commitdddddds'
      
  npmrc2:
    image: mhart/alpine-node
    commands:
      - npm i express
      
  maven:
    image: maven
    commands:
      - mvn clean package
  sbt:
    image: sbt
    commands:
      - sbt 

  gradle:
    image: gradle
    commands:
      - gradle
