pipeline:
  huh:
    image: busybox
    commands:
    - ifconfig
    - cat /etc/resolv.conf
    - cat /etc/hosts
    
  please:
    image: nexus.admin.sharecare.com/drone-nexus-docker:4.4.1
    environment:
      PLUGIN_DAEMON_OFF: true
    pull: true
    version: jq -r .version package.json
    
  npmrc:
    image: mhart/alpine-node
    environment:
      - NPM_CONFIG_USERCONFIG=/secrets/.npmrc
    commands:
      - nslookup nexus.admin.sharecare.com
      - apk add --no-cache --update curl
      - curl -vs https://nexus.admin.sharecare.com -o /dev/null
      - npm i @sharecare/maestro-dsl
    
