pipeline:  
  something:
    image: busybox
    commands: 
      - ls -alRt /secrets
      - cat /secrets/.npmrc || true
      - cp /secrets/.npmrc $HOME/.npmrc && ls -al $HOME && cat $HOME/.npmrc
    volumes:
      - /secrets:/secrets

  docker:
    image: docker.io/plugins/docker
    repo: cloudsc/delete-me
    commands:
      - cat /etc/resolv.conf
    secrets: [ docker_username, docker_password ]
