pipeline:
  wheeee:
    image: nexus.admin.sharecare.com/ftech-server-cicd-take-tag:1.0.2
      
  mount-cache:
    image: nexus.admin.sharecare.com/sso-scala-deps-cache:1.0
    commands:
      - cp -a /root/.ivy2 .
      - cp -a /root/.sbt .
      
  whee:
    image: nexus.admin.sharecare.com/drone-nexus-docker
    version: jq -r .version package.json

  assemble:
    image: gempesaw/docker-sbt:0.13.11
    commands:
      - yes | cp -rf .ivy2/* /root/.ivy2/
      - yes | cp -rf .sbt/* /root/.sbt/
      - mkdir -p $HOME/.sbt/0.13/plugins/
      - cp /secrets/.credentials $HOME/.ivy2/
      - cp /secrets/credentials.sbt $HOME/.sbt/0.13/plugins/plugins.sbt
      - sbt run
